import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Arweave from 'arweave';
import { useEffect, useState } from 'react';
import { ArweaveWebWallet } from 'arweave-wallet-connector'
import { getVouchedUsers } from '../services/discord'

const arweave = Arweave.init({
  host: 'arweave.net',
  port: 443,
  protocol: 'https'
});

export default function Home() {
  const [address, setAddress] = useState()
  const users = getVouchedUsers()

  console.log(users)
  const wallet = new ArweaveWebWallet({
    name: 'Connector Example',
    logo: 'https://jfbeats.github.io/ArweaveWalletConnector/placeholder.svg'
  })

  const connect = async () => {
    if (!address) {
      if (!window.arweaveWallet) {
        window.open("https://arconnect.io", "_blank");
      }
      await arweaveWallet.connect(["ACCESS_ADDRESS", "SIGN_TRANSACTION"], {
        name: "Vouch DAO v0",
      });
      setAddress(await arweaveWallet.getActiveAddress());
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Vouch Discord</h1>
        <div className="w-1/2 p-12">
          <h4 className="mb-4 text-md tracking-tight leading-none text-gray-900 md:text-lg lg:text-xl dark:text-white">Vouch Discord Service is a registered server of Vouch DAO, this server allows users to leverage the power of Discord to create a Vouch Record for Web of Value Services.</h4>
          <h4 className="mb-4 text-md tracking-tight leading-none text-gray-900 md:text-lg lg:text-xl dark:text-white">Connect wallet to get started</h4>
        </div>
        <div className='flex flex-col content-center'>
          {
            address ? (
              <button type="button" onClick={() => window.location.href = process.env.NEXT_PUBLIC_DISCORD_ENDPOINT + `&state=${address}`} className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Authenticate {`${address.slice(0, 8)}...${address.slice(address.length - 8)}`} with Discord</button>
            )
              :
              <button type="button" onClick={connect} className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Connect Wallet</button>
          }
        </div>
      </main>
    </div>
  )
}
